### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by satnaing** [eimg/rsd25#1]
I noticed a typo in README.

> Authentication, Tailwind CSS, shadcn/ui စသည့် ဆက်စပ်နည်းပညာများလည်း ပါဝင်သည်။ React နှင့် ရေးသားသည့် Social Media ပရာဂျက်တစ်ခု၊ React Native နှင့် ရေးသားသည့် Pay App UI တစ်ခု၊ Next.js နှင့် ရေးသားသည့် Mobie Directory တစ်ခု စုစုပေါင်း လက်တွေ့နမူနာပရောဂျက် (၃) ခုပါဝင်သည်။

`Mobie Directory` 👈🏼

Thank you so much for the book and this repo.

**Comment by eimg** [comment]
ကျေးဇူးပါ၊ Update  တင်တဲ့အခါ ပြင်ပေးလိုက်ပါမယ်
